---
abstract: 'Test fallback behaviour in absence of modules'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  File::Find: '0'
  File::Spec: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Without-Module
no_index:
  directory:
    - t
    - inc
provides:
  Test::Without::Module:
    file: lib/Test/Without/Module.pm
    version: '0.20'
requires:
  Carp: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Corion/test-without-module.git
version: '0.20'
x_static_install: 1
